### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by salaheddinelhamraoui** [podcoder/flutter_localization#1]
hi, thanks for this source code
it gives me this error in the console when I change the language 

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The getter 'itemHeights' was called on null.
Receiver: null
Tried calling: itemHeights
The relevant error-causing widget was: 
  MaterialApp file:///D:/Flutter/flutter_projects/flutter_localization/lib/main.dart:50:14

do you know why?

**Comment by mirkarpude** [comment]
> you know why?

+1

**Comment by podcoder** [comment]
This is happening because the "change language dropdown or any other dropdown" popup is still open and the language is changed.
Just for hint, check your dropdown implementation and for a quick test use the following chunk of code when changing the language.

```dart
Future.delayed(const Duration(milliseconds: 300), (){
        /// Change your locale..
 });```

**Comment by mirkarpude** [comment]
My error at translate (not in set)
error while translate title/hintText, etc text
The method 'translate' was called on null. Receiver: null Tried calling: translate("home_page")

**Comment by podcoder** [comment]
@mirkarpude It would be better if you share the code, from your `main.dart`, and also from your `app_localization` file.
Because as it seems from your error, you are missing something in the implementation of Localization.

**Comment by mirkarpude** [comment]
import 'package:flutter/services.dart';
import 'package:flutter/material.dart';

import 'package:konnedu_basic/config/app_localization.dart';
import 'package:konnedu_basic/config/constants.dart';
import 'package:konnedu_basic/router/custom_router.dart';
import 'package:konnedu_basic/router/route_constants.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
 import 'package:shared_preferences/shared_preferences.dart';
import 'config/language_constants.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await SystemChrome.setPreferredOrientations(<DeviceOrientation>[DeviceOrientation.portraitUp, DeviceOrientation.portraitDown])
      .then((_) => runApp(MyApp()));
}

class MyApp extends StatefulWidget {
  const MyApp({Key key}) : super(key: key);
  
 static void setLocale(BuildContext context, Locale newLocale) async{
   _MyAppState state = context.findAncestorStateOfType<_MyAppState>();
   state.setLocale(newLocale);
 }  

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  Locale _locale;

  setLocale(Locale locale) {
    setState(() {
      _locale = locale;
    });
  }

   @override
  void didChangeDependencies() {
    this._fetchLocale().then((locale) {
      setState(() {
        this._locale = locale;
      });
    });
    super.didChangeDependencies();
  }

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
     if (this._locale == null) {
      return Container(
        child: Center(
          child: CircularProgressIndicator(
              valueColor: AlwaysStoppedAnimation(Theme.of(context).accentColor),
        ),
      ));
    } else {
    return MaterialApp(
      title: Constants.appName,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      supportedLocales: [
          Locale('en', 'US'),
          Locale('mr', 'IN'),
          Locale('hi', 'IN'),
        ],
        locale: _locale,
        localizationsDelegates: [
          AppLocalizationsDelegate(),
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate
        ],
        localeResolutionCallback: (locale, supportedLocales) {
          for (var supportedLocale in supportedLocales) {
            if (supportedLocale.languageCode == locale.languageCode &&
                supportedLocale.countryCode == locale.countryCode) {
              return supportedLocale;
            }
          }
          return supportedLocales.first;
        },
      debugShowCheckedModeBanner: false,
      onGenerateRoute: CustomRouter.generatedRoute,
      
      initialRoute: splashRoute,
      //home: SplashPage(),
    );
  //}
  }
}

_fetchLocale() async {
    Locale tempLocale;

    SharedPreferences prefs = await SharedPreferences.getInstance();
    String languageCode = (prefs.getString(LAGUAGE_CODE) ?? 'en');

    switch (languageCode) {
      case ENGLISH:
        tempLocale = Locale(ENGLISH, 'US');
        break;
      case MARATHI:
        tempLocale = Locale(MARATHI, 'IN');
        break;
      case MARATHI:
        tempLocale = Locale(HINDI, 'IN');
        break;
      //case URDU:
       // tempLocale = Locale(URDU, 'IN');
       // break;
      default:
        tempLocale = Locale(ENGLISH, 'US');
    }
    return tempLocale;
  }
}

// -----------
`
**app_localization**

`import 'dart:convert';
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  Map<String, String> _localizedValues;

  Future<bool> load() async {
    String jsonStringValues =
        await rootBundle.loadString('lib/config/lang/${locale.languageCode}.json');
    Map<String, dynamic> mappedJson = json.decode(jsonStringValues);
    _localizedValues =
        mappedJson.map((key, value) => MapEntry(key, value.toString()));
        return true;
  }

  String translate(String key) {
    return _localizedValues[key];
  }

}

class AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    // return ['en', 'mr', 'ur', 'hi'].contains(locale.languageCode);
    return ['en', 'mr', 'hi'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    AppLocalizations localization = new AppLocalizations(locale);
    await localization.load();
    return localization;
  }

  @override
  bool shouldReload(LocalizationsDelegate<AppLocalizations> old) => false;
}

String buildTranslate(BuildContext context, String key) {
print(AppLocalizations.of(context));
  return  AppLocalizations.of(context).translate(key);
}`

**setting page**

`import 'package:flutter/material.dart';
import 'package:konnedu_basic/config/languages.dart';
import 'package:konnedu_basic/config/language_constants.dart';
import 'package:konnedu_basic/config/app_localization.dart';
import 'package:konnedu_basic/main.dart';
 import 'package:shared_preferences/shared_preferences.dart';

class SettingsPage extends StatefulWidget {
  SettingsPage({Key key}) : super(key: key);

  @override
  _SettingsPageState createState() => _SettingsPageState();
}

class _SettingsPageState extends State<SettingsPage> {
  
    void _changeLanguage(String languageCode) async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    await prefs.setString(LAGUAGE_CODE, languageCode);
    Locale locale;
    switch (languageCode) {
      case ENGLISH:
        locale = Locale(languageCode, 'US');
        break;
      case MARATHI:
        locale = Locale(languageCode, 'IN');
        break;
      case HINDI:
        locale = Locale(languageCode, 'IN');
    }
    MyApp.setLocale(context, locale);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(buildTranslate(context, 'settings')),
      ),
      body: Container(
        child: Center(
            child: DropdownButton<Languages>(
          iconSize: 30,
          hint: Text(buildTranslate(context, 'change_language')),
          onChanged: (Languages language) {
            _changeLanguage(language.name);
          },
          items: Languages.languageList()
              .map<DropdownMenuItem<Languages>>(
                (e) => DropdownMenuItem<Languages>(
                  value: e,
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceAround,
                    children: <Widget>[
                      
                      Text(e.name)
                    ],
                  ),
                ),
              )
              .toList(),
        )),
      ),
    );
  }
}`

**Usage**
in any other widgets e.g
title: Text(buildTranslate(context, 'home_page')),

**Comment by podcoder** [comment]
On `onChanged` value of the `Dropdown` you are passing the `language.name`, where as in your `_onChanged` method you need to pass 'languageCode`.
Try changing it to `language.code`

**Comment by salaheddinelhamraoui** [comment]
please can check my code :

main.dart

```
import 'package:flutter/material.dart';
import 'package:flutter_localization_master/localization/demo_localization.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'screens/home_page.dart';
import 'screens/setting_page.dart';
import 'localization/language_constants.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  const MyApp({Key key}) : super(key: key);
  static void setLocale(BuildContext context, Locale newLocale) {
    _MyAppState state = context.findAncestorStateOfType<_MyAppState>();
    state.setLocale(newLocale);
  }

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  Locale _locale;
  setLocale(Locale locale) {
    setState(() {
      _locale = locale;
    });
  }

  @override
  void didChangeDependencies() {
    getLocale().then((locale) {
      setState(() {
        this._locale = locale;
      });
    });
    super.didChangeDependencies();
  }

  @override
  Widget build(BuildContext context) {
    if (this._locale == null) {
      return Container(
        child: Center(
          child: CircularProgressIndicator(
              valueColor: AlwaysStoppedAnimation<Color>(Colors.blue[800])),
        ),
      );
    } else {
      return MaterialApp(
        debugShowCheckedModeBanner: false,
        title: "Flutter Localization Demo",
        theme: ThemeData(primarySwatch: Colors.blue, fontFamily: 'Janna'),
        locale: _locale,
        supportedLocales: [
          Locale("en", "US"),
          Locale("ar", "SA"),
        ],
        localizationsDelegates: [
          DemoLocalization.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
        localeResolutionCallback: (locale, supportedLocales) {
          for (var supportedLocale in supportedLocales) {
            if (supportedLocale.languageCode == locale.languageCode &&
                supportedLocale.countryCode == locale.countryCode) {
              return supportedLocale;
            }
          }
          return supportedLocales.first;
        },
        initialRoute: HomePage.id,
        routes: {
          // When navigating to the "/" route, build the FirstScreen widget.
          HomePage.id: (context) => HomePage(),
          SettingsPage.id: (context) => SettingsPage(),
        },
      );
    }
  }
}
```

Setting Page 

```
import 'package:flutter/material.dart';
import 'package:flutter_localization_master/classes/language.dart';
import 'package:flutter_localization_master/localization/language_constants.dart';
import 'package:flutter_localization_master/main.dart';

class SettingsPage extends StatefulWidget {
  SettingsPage({Key key}) : super(key: key);
  static String id = 'settingPage';
  @override
  _SettingsPageState createState() => _SettingsPageState();
}

class _SettingsPageState extends State<SettingsPage> {
  void _changeLanguage(Language language) async {
    Locale _locale = await setLocale(language.languageCode);
    MyApp.setLocale(context, _locale);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(getTranslated(context, 'settings')),
      ),
      body: Container(
        child: Center(
            child: DropdownButton<Language>(
          iconSize: 30,
          hint: Text(getTranslated(context, 'change_language')),
          onChanged: (Language language) {
            _changeLanguage(language);
          },
          items: Language.languageList()
              .map<DropdownMenuItem<Language>>(
                (e) => DropdownMenuItem<Language>(
                  value: e,
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceAround,
                    children: <Widget>[
                      Text(
                        e.flag,
                        style: TextStyle(fontSize: 30),
                      ),
                      Text(e.name)
                    ],
                  ),
                ),
              )
              .toList(),
        )),
      ),
    );
  }
}


```



Home Page

```
import 'package:flutter/material.dart';
import 'package:flutter_localization_master/classes/language.dart';
import 'package:flutter_localization_master/localization/language_constants.dart';
import 'package:flutter_localization_master/main.dart';
import 'package:flutter_localization_master/components/drawerList.dart';

class HomePage extends StatefulWidget {
  HomePage({Key key}) : super(key: key);

  static String id = "HomePage";
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final GlobalKey<FormState> _key = GlobalKey<FormState>();

  void _changeLanguage(Language language) async {
    Locale _locale = await setLocale(language.languageCode);
    MyApp.setLocale(context, _locale);
  }

  void _showSuccessDialog() {
    showTimePicker(context: context, initialTime: TimeOfDay.now());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(getTranslated(context, 'home_page')),
        actions: <Widget>[
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: DropdownButton<Language>(
              underline: SizedBox(),
              icon: Icon(
                Icons.translate,
                color: Colors.white,
              ),
              onChanged: (Language language) {
                _changeLanguage(language);
              },
              items: Language.languageList()
                  .map<DropdownMenuItem<Language>>(
                    (e) => DropdownMenuItem<Language>(
                      value: e,
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceAround,
                        children: <Widget>[
                          Text(
                            e.flag,
                            style: TextStyle(fontSize: 30),
                          ),
                          Text(e.name)
                        ],
                      ),
                    ),
                  )
                  .toList(),
            ),
          ),
        ],
      ),
      drawer: Drawer(
        child: drawerList(context),
      ),
      body: Container(
        padding: EdgeInsets.all(20),
        child: Container(
          height: MediaQuery.of(context).size.height / 4,
          child: Center(
            child: Text(
              getTranslated(context, 'personal_information'),
              // DemoLocalization.of(context).translate('personal_information'),
              textAlign: TextAlign.center,
              style: TextStyle(
                fontFamily: getTranslated(context, 'font'),
                fontSize: 30,
                fontWeight: FontWeight.bold,
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```


DemoLocalization 

```
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class DemoLocalization {
  DemoLocalization(this.locale);

  final Locale locale;
  static DemoLocalization of(BuildContext context) {
    return Localizations.of<DemoLocalization>(context, DemoLocalization);
  }

  Map<String, String> _localizedValues;

  Future<void> load() async {
    String jsonStringValues =
        await rootBundle.loadString('lib/lang/${locale.languageCode}.json');
    Map<String, dynamic> mappedJson = json.decode(jsonStringValues);
    _localizedValues =
        mappedJson.map((key, value) => MapEntry(key, value.toString()));
  }

  String translate(String key) {
    return _localizedValues[key];
  }

  // static member to have simple access to the delegate from Material App
  static const LocalizationsDelegate<DemoLocalization> delegate =
      _DemoLocalizationsDelegate();
}

class _DemoLocalizationsDelegate
    extends LocalizationsDelegate<DemoLocalization> {
  const _DemoLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'ar'].contains(locale.languageCode);
  }

  @override
  Future<DemoLocalization> load(Locale locale) async {
    DemoLocalization localization = new DemoLocalization(locale);
    await localization.load();
    return localization;
  }

  @override
  bool shouldReload(LocalizationsDelegate<DemoLocalization> old) => false;
}

```

language_constants

```
import 'package:flutter/material.dart';
import 'package:flutter_localization_master/localization/demo_localization.dart';
import 'package:shared_preferences/shared_preferences.dart';

const String LAGUAGE_CODE = 'languageCode';

//languages code
const String ENGLISH = 'en';
const String ARABIC = 'ar';

Future<Locale> setLocale(String languageCode) async {
  SharedPreferences _prefs = await SharedPreferences.getInstance();
  await _prefs.setString(LAGUAGE_CODE, languageCode);
  return _locale(languageCode);
}

Future<Locale> getLocale() async {
  SharedPreferences _prefs = await SharedPreferences.getInstance();
  String languageCode = _prefs.getString(LAGUAGE_CODE) ?? "en";
  return _locale(languageCode);
}

Locale _locale(String languageCode) {
  switch (languageCode) {
    case ENGLISH:
      return Locale(ENGLISH, 'US');
    case ARABIC:
      return Locale(ARABIC, "SA");
    default:
      return Locale(ENGLISH, 'US');
  }
}

String getTranslated(BuildContext context, String key) {
  return DemoLocalization.of(context).translate(key);
}

```


the language changed fine but it keeps giving me this error

```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during performLayout():
The getter 'itemHeights' was called on null.
Receiver: null
Tried calling: itemHeights

The relevant error-causing widget was: 
  MaterialApp file:///D:/Flutter/flutter_projects/First%20Cours/flutter_localization/lib/main.dart:49:14
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _DropdownButtonState._handleTap.<anonymous closure> (package:flutter/src/material/dropdown.dart:1149:26)
#2      _RenderMenuItem.performLayout (package:flutter/src/material/dropdown.dart:619:5)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#4      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
...
The following RenderObject was being processed when the exception was fired: _RenderMenuItem#15ec2 relayoutBoundary=up26 NEEDS-LAYOUT NEEDS-PAINT
...  parentData: offset=Offset(16.0, 0.0) (can use size)
...  constraints: BoxConstraints(w=122.0, 0.0<=h<=Infinity)
...  size: Size(122.0, 48.0)
RenderObject: _RenderMenuItem#15ec2 relayoutBoundary=up26 NEEDS-LAYOUT NEEDS-PAINT
  parentData: offset=Offset(16.0, 0.0) (can use size)
  constraints: BoxConstraints(w=122.0, 0.0<=h<=Infinity)
  size: Size(122.0, 48.0)
...  child: RenderConstrainedBox#e4b57 relayoutBoundary=up27 NEEDS-PAINT
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(w=122.0, 0.0<=h<=Infinity)
...    size: Size(122.0, 48.0)
...    additionalConstraints: BoxConstraints(0.0<=w<=Infinity, 48.0<=h<=Infinity)
...    child: RenderPositionedBox#51dff relayoutBoundary=up28 NEEDS-PAINT
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=122.0, 48.0<=h<=Infinity)
...      size: Size(122.0, 48.0)
...      alignment: AlignmentDirectional.centerStart
...      textDirection: rtl
...      widthFactor: expand
...      heightFactor: expand
...      child: RenderFlex#c60e2 relayoutBoundary=up29 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 6.5) (can use size)
...        constraints: BoxConstraints(0.0<=w<=122.0, 0.0<=h<=Infinity)
...        size: Size(122.0, 35.0)
...        direction: horizontal
...        mainAxisAlignment: spaceAround
...        mainAxisSize: max
...        crossAxisAlignment: center
...        textDirection: rtl
...        verticalDirection: down
...        child 1: RenderParagraph#4f669 relayoutBoundary=up30 NEEDS-PAINT
...          parentData: offset=Offset(76.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(unconstrained)
...          size: Size(38.0, 35.0)
...          textAlign: start
...          textDirection: rtl
...          softWrap: wrapping at box width
...          overflow: clip
...          locale: ar_SA
...          maxLines: unlimited
...        child 2: RenderParagraph#8b8f5 relayoutBoundary=up30 NEEDS-PAINT
...          parentData: offset=Offset(8.0, 2.5); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(unconstrained)
...          size: Size(52.0, 30.0)
...          textAlign: start
...          textDirection: rtl
...          softWrap: wrapping at box width
...          overflow: clip
...          locale: ar_SA
...          maxLines: unlimited
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The getter 'itemHeights' was called on null.
Receiver: null
Tried calling: itemHeights
The relevant error-causing widget was: 
  MaterialApp file:///D:/Flutter/flutter_projects/First%20Cours/flutter_localization/lib/main.dart:49:14
════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by podcoder** [comment]
@salaheddinelhamraoui 
I just copied and pasted your code and it's working perfectly for me.
only the `drawer list` is not there

**Comment by podcoder** [comment]
@salaheddinelhamraoui 
If you want I can share the code with you

**Comment by mirkarpude** [comment]
I have flutter new ver. 1.17,
Is that a issue?

**Comment by salaheddinelhamraoui** [comment]
> @salaheddinelhamraoui
> If you want I can share the code with you

OK please share it with me.

**Comment by podcoder** [comment]
> I have flutter new ver. 1.17,
> Is that a issue?

No, Because my Flutter version is also 1.17

**Comment by mirkarpude** [comment]
> On `onChanged` value of the `Dropdown` in SettingsPage, you are passing the `language.name`, where as in your `_onChanged` method you need to pass `languageCode`.
> Try changing it to `language.languageCode`

error occurred at translate (usage) at any widget, 
not in set

**Comment by mirkarpude** [comment]
**After Rebuild**

I/flutter (17781): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (17781): The following assertion was thrown building SettingsPage(dirty, dependencies:
I/flutter (17781): [_LocalizationsScope-[GlobalKey#15446]], state: _SettingsPageState#00f6c):
I/flutter (17781): A non-null String must be provided to a Text widget.
I/flutter (17781): 'package:flutter/src/widgets/text.dart':
I/flutter (17781): Failed assertion: line 298 pos 10: 'data != null'
I/flutter (17781):
I/flutter (17781): The relevant error-causing widget was:
I/flutter (17781):   SettingsPage
I/flutter (17781):   
lib\…\navigationhome\navigation_home_screen.dart:73
I/flutter (17781):
I/flutter (17781): When the exception was thrown, this was the stack:
I/flutter (17781): (elided 5 frames from class _AssertionError and dart:async)
I/flutter (17781):
I/flutter (17781): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by podcoder** [comment]
> **After Rebuild**
> 
> I/flutter (17781): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
> I/flutter (17781): The following assertion was thrown building SettingsPage(dirty, dependencies:
> I/flutter (17781): [_LocalizationsScope-[GlobalKey#15446]], state: _SettingsPageState#00f6c):
> I/flutter (17781): A non-null String must be provided to a Text widget.
> I/flutter (17781): 'package:flutter/src/widgets/text.dart':
> I/flutter (17781): Failed assertion: line 298 pos 10: 'data != null'
> I/flutter (17781):
> I/flutter (17781): The relevant error-causing widget was:
> I/flutter (17781): SettingsPage
> I/flutter (17781):
> lib\…\navigationhome\navigation_home_screen.dart:73
> I/flutter (17781):
> I/flutter (17781): When the exception was thrown, this was the stack:
> I/flutter (17781): (elided 5 frames from class _AssertionError and dart:async)
> I/flutter (17781):
> I/flutter (17781): ════════════════════════════════════════════════════════════════════════════════════════════════════

A non-null String must be provided to a Text widget.
This error means you are supplying a `null` value to a `Text` widget.

can You Share your `Settings.dart` also with the json files
